### ISSUE TITLE
因获取临时素材未解析http头，无法获取文件类型、文件名等返回信息

### ISSUE THREAD

**Issue by 9aceh** [go-laoji/wecom-go-sdk#12]
企业微信API文档：https://developer.work.weixin.qq.com/document/path/90254
![image](https://github.com/user-attachments/assets/07557b7a-0c81-495b-b6ba-be65d79b766c)
最主要的是没返回文件类型，基本上没发用

**Comment by 9aceh** [comment]
目前需求是需要转存文件，获取临时素材的方法没有返回 Content-disposition 不知道文件名，没法处理

**Comment by go-laoji** [comment]
[v2.1.0 ](https://github.com/go-laoji/wecom-go-sdk/releases/tag/v2.1.0) 新版本支持，返回http.Header
