### ISSUE TITLE
token过期,删除全部缓存,导致的问题

### ISSUE THREAD

**Issue by yiGmMk** [go-laoji/wecom-go-sdk#13]
启动时设置的http重试策略:有token过期就丢弃全部缓存,在部分场景会导致不可用[企业微信的suite_ticket,10分钟推送一次,删除后,10分钟内需要手动刷新获取,没刷新时这期间需要用到suite_ticket的接口就会报错]
`
ww.httpClient.AddRetryCondition(func(r *resty.Response, err error) bool {
		var biz internal.BizResponse
		json.Unmarshal(r.Body(), &biz)
		if biz.ErrCode == 42001 {
			ww.cache.DropAll()
			return true
		}
		return false
	})
`
![image](https://github.com/user-attachments/assets/98bf9dd7-17fb-4c17-86bf-de960eabf83a)

我目前修复的策略是只删除corp相关的token,其他的不删,其他人有遇到过吗
ww.cache.DropPrefix([]byte("corpToken"))

**Comment by go-laoji** [comment]
确实忘记了这个三方suite_ticket的问题，估计很少有人用这个项目的。可以接个PR
