### ISSUE TITLE
懒得pull request了，能不能加两个接口，我发现还没有的

### ISSUE THREAD

**Issue by jiangchangren** [go-laoji/wecom-go-sdk#3]
设置企业的许可自动激活状态
https://developer.work.weixin.qq.com/document/path/95873

获取应用的管理员列表
https://developer.work.weixin.qq.com/document/path/90606

**Comment by go-laoji** [comment]
ok先安排上

**Comment by go-laoji** [comment]
v1.5.4　已发布
