### ISSUE TITLE
大佬，MessageSend方法中的corpId参数是什么呀？怎么获取？

### ISSUE THREAD

**Issue by TimeBye** [go-laoji/wecom-go-sdk#5]
大佬，MessageSend方法中的corpId参数是什么呀？怎么获取？

https://github.com/go-laoji/wecom-go-sdk/blob/026bef1f65d47eaf26f2e15ea9f17b821d22684f/message.go#L129-L136

**Comment by go-laoji** [comment]
https://github.com/go-laoji/wecom-go-sdk/blob/develop/suite.go#L254

看下这个，是把所有企业授权信息放到了数据库的，当然也可以实现SetAppSecretFunc接口自定义获取

例子


```
wecomSdk.SetAppSecretFunc(func(corpId uint) (corpid string, secret string, customizedApp bool) {
    switch corpId {
    case 1:
      return CorpId, "自建应用的secret", true
    case 2:
      return CorpId, "通讯录助手的secret", true
    }
  })
```

**Comment by TimeBye** [comment]
好的  谢谢大佬
